apiVersion: v1
kind: PersistentVolume
metadata:
  name: enzyme-jenkins
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-056c3faa6745b2582