kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: enzyme-jenkins
  namespace: enzyme-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: gp2
  volumeName: enzyme-jenkins