apiVersion: v1
kind: PersistentVolume
metadata:
  name: <jenkinsHostName>-jenkins
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: <volumeID>
